### ISSUE TITLE
Enable null-safety

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#89]
We are blocked by: `intl_translation` not support null safety

```
Because intl_translation 0.17.10+1 depends on intl >=0.15.3 <0.17.0 and linshare_flutter_app depends on intl 0.17.0-nullsafety.2, intl_translation 0.17.10+1 is forbidden.
```

**Comment by hoangdat** [comment]
Work with: 
```
Flutter 1.24.0-8.0.pre.251 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 836efaecf0 (9 weeks ago) • 2020-11-13 21:51:04 -0800
Engine • revision e06f106385
Tools • Dart 2.12.0 (build 2.12.0-40.0.dev)
```

But it is blocked by `Dio` not support null safety. 

(Dio in domain for `CancelToken`)

**Comment by hoangdat** [comment]
> We are blocked by: `intl_translation` not support null safety
> 
> ```
> Because intl_translation 0.17.10+1 depends on intl >=0.15.3 <0.17.0 and linshare_flutter_app depends on intl 0.17.0-nullsafety.2, intl_translation 0.17.10+1 is forbidden.
> ```

Resolved by: https://github.com/hoangdat/intl_translation/commit/d37450bb9228011fea0734f3bea0976730e22e0e

**Comment by huynguyennovem** [comment]
```
E/AndroidRuntime( 1549): FATAL EXCEPTION: pool-6-thread-1
E/AndroidRuntime( 1549): Process: com.linagora.android.linshare, PID: 1549
E/AndroidRuntime( 1549): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 1549): 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
E/AndroidRuntime( 1549): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 1549): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 1549): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 1549): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 1549): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 1549): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 1549): Caused by: java.lang.IllegalArgumentException: Invalid column account_type
E/AndroidRuntime( 1549): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/AndroidRuntime( 1549): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
E/AndroidRuntime( 1549): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
E/AndroidRuntime( 1549): 	at android.content.ContentResolver.query(ContentResolver.java:1183)
E/AndroidRuntime( 1549): 	at android.content.ContentResolver.query(ContentResolver.java:1115)
E/AndroidRuntime( 1549): 	at android.content.ContentResolver.query(ContentResolver.java:1071)
E/AndroidRuntime( 1549): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.getContactsForEmailOrName(ContactsServicePlugin.java:535)
E/AndroidRuntime( 1549): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$700(ContactsServicePlugin.java:54)
E/AndroidRuntime( 1549): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:436)
E/AndroidRuntime( 1549): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:412)
E/AndroidRuntime( 1549): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/AndroidRuntime( 1549): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 1549): 	... 3 more
```

**Comment by hoangdat** [comment]
/spend 8h
Dat /spend 4h
